### ISSUE TITLE
Tortoise ORM 使用await提示数据库未连接

### ISSUE THREAD

**Issue by li7pd** [cary997/fastapi-naive-admin#2]
修改点
1. 将数据库配置修改成自己的
2. routes.py，路由配置只使用自己的
3. models.__init__.py，只引入了自己的数据模型
4. 增加自己的api
`@router.get('/get_user_info', summary="获取用户信息", response_model=users_schema.UserGetResponse)
async def get_user_info(email: str=Query(None)):
    query = {}
    if email:
        query.setdefault('email', email)
    
    try:
        # 查询结果
        query_data = await UserInfo.get_or_none(**query)
        #
        user = await users_schema.UserInfoResult.from_tortoise_orm(query_data)
        user_dict = user.model_dump()
        # #
        logger.info(f"获取用户信息: {user_dict}")
    except Exception as e:
        logger.error(e)
        raise HTTPException(status_code=500, detail="Database connection error")
    
    if not query_data:
        return success(message="查询结果为空!")
    else:
        return success(data=[])`
请求接口提示数据库未连接，以下是报错信息
ERROR | apis.solvely.solvely_api:get_user_info:47 - Can't connect to MySQL server: 后面是配置信息

如果api里自己在配置一个数据库连接是可以正常连接并且请求查询成功
另外如果是启动未修改的版本，就可以正常走自带的请求，请问是哪里的配置没有进行同步修改

**Comment by cary997** [comment]
我觉得问题出在 models/__init__.py 这个文件，麻烦贴出来看下

**Comment by li7pd** [comment]
models.__init__.py
<img width="1321" alt="image" src="https://github.com/user-attachments/assets/38d524ea-e850-4cba-a6e1-3d554a0d3f6a">

模型文件
<img width="955" alt="image" src="https://github.com/user-attachments/assets/67d3649e-525f-4499-a07b-bff5fe5eacf3">

补充信息：
1. 如果使用本地数据库，可以正常查询数据
2. 更换成公司云数据库（都是mysql），就会提示数据库连接失败，但是在api里手动创建注册一个连接，也能正常查询

**Comment by cary997** [comment]
> 模型。**初始化**.py <img alt="图像" width="1321" src="https://private-user-images.githubusercontent.com/165650646/357775806-38d524ea-e850-4cba-a6e1-3d554a0d3f6a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM2MzI3NDUsIm5iZiI6MTcyMzYzMjQ0NSwicGF0aCI6Ii8xNjU2NTA2NDYvMzU3Nzc1ODA2LTM4ZDUyNGVhLWU4NTAtNGNiYS1hNmUxLTNkNTU0YTBkM2Y2YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxNFQxMDQ3MjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02YzM4MmFjZTA5NjBkZmE5MjIzOWFjOTkxNDM4OGMwYmVhNDY3M2VkOWYyZjMxNWViNmRjMThlYzNhY2JmYjcyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Lg6SNqphshNZ1QAT6QS8qwXzD94Efe3C85Ov-akAheY">
> 
> 模型文件 <img alt="图像" width="955" src="https://private-user-images.githubusercontent.com/165650646/357776233-67d3649e-525f-4499-a07b-bff5fe5eacf3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM2MzI3NDUsIm5iZiI6MTcyMzYzMjQ0NSwicGF0aCI6Ii8xNjU2NTA2NDYvMzU3Nzc2MjMzLTY3ZDM2NDllLTUyNWYtNDQ5OS1hMDdiLWJmZjVmZTVlYWNmMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxNFQxMDQ3MjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNDM1NWMzYTE2OThiMmNkYmM5MDkyYTE3ODgyMjhiYmZkNDMyOTZlMmFlYjAzMTA2ZWIxNTVmOTMzMTc4NWEyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.5HOtZvoWj4DXgi-v-hdD_9vFw3ITSIvMdZiP9x_XEEw">
> 
> 补充信息：
> 
> 1. 如果使用本地数据库，可以正常查询数据
> 2. 更换成公司云数据库（都是mysql），就会提示数据库连接失败，但是在api里手动创建注册一个连接，也能正常查询

这么看来更像是数据库连接配置问题，你可以试试将手动创建注册链接的配置替换extend/datebase/init.py中的连接配置

**Comment by li7pd** [comment]
> > 模型。**初始化**.py <img alt="图像" width="1321" src="https://private-user-images.githubusercontent.com/165650646/357775806-38d524ea-e850-4cba-a6e1-3d554a0d3f6a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM2MzI3NDUsIm5iZiI6MTcyMzYzMjQ0NSwicGF0aCI6Ii8xNjU2NTA2NDYvMzU3Nzc1ODA2LTM4ZDUyNGVhLWU4NTAtNGNiYS1hNmUxLTNkNTU0YTBkM2Y2YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxNFQxMDQ3MjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02YzM4MmFjZTA5NjBkZmE5MjIzOWFjOTkxNDM4OGMwYmVhNDY3M2VkOWYyZjMxNWViNmRjMThlYzNhY2JmYjcyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Lg6SNqphshNZ1QAT6QS8qwXzD94Efe3C85Ov-akAheY">
> > 模型文件 <img alt="图像" width="955" src="https://private-user-images.githubusercontent.com/165650646/357776233-67d3649e-525f-4499-a07b-bff5fe5eacf3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM2MzI3NDUsIm5iZiI6MTcyMzYzMjQ0NSwicGF0aCI6Ii8xNjU2NTA2NDYvMzU3Nzc2MjMzLTY3ZDM2NDllLTUyNWYtNDQ5OS1hMDdiLWJmZjVmZTVlYWNmMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxNFQxMDQ3MjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNDM1NWMzYTE2OThiMmNkYmM5MDkyYTE3ODgyMjhiYmZkNDMyOTZlMmFlYjAzMTA2ZWIxNTVmOTMzMTc4NWEyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.5HOtZvoWj4DXgi-v-hdD_9vFw3ITSIvMdZiP9x_XEEw">
> > 补充信息：
> > 
> > 1. 如果使用本地数据库，可以正常查询数据
> > 2. 更换成公司云数据库（都是mysql），就会提示数据库连接失败，但是在api里手动创建注册一个连接，也能正常查询
> 
> 这么看来更像是数据库连接配置问题，你可以试试将手动创建注册链接的配置替换extend/datebase/init.py中的连接配置

手动替换extend/datebase/init.py中的连接配置，可以正常连接到数据库并且查询到了，但这个很奇怪，我也尝试将他们都打印出来对比下是哪个环节传递出的问题

**Comment by cary997** [comment]
可以将你的联系方式发到我邮箱yaoleiguo@gmail.com 我可以远程给你看下

**Comment by cary997** [comment]
> > > 模型。**初始化**.py <img alt="图像" width="1321" src="https://private-user-images.githubusercontent.com/165650646/357775806-38d524ea-e850-4cba-a6e1-3d554a0d3f6a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM2MzI3NDUsIm5iZiI6MTcyMzYzMjQ0NSwicGF0aCI6Ii8xNjU2NTA2NDYvMzU3Nzc1ODA2LTM4ZDUyNGVhLWU4NTAtNGNiYS1hNmUxLTNkNTU0YTBkM2Y2YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxNFQxMDQ3MjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02YzM4MmFjZTA5NjBkZmE5MjIzOWFjOTkxNDM4OGMwYmVhNDY3M2VkOWYyZjMxNWViNmRjMThlYzNhY2JmYjcyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Lg6SNqphshNZ1QAT6QS8qwXzD94Efe3C85Ov-akAheY">
> > > 模型文件 <img alt="图像" width="955" src="https://private-user-images.githubusercontent.com/165650646/357776233-67d3649e-525f-4499-a07b-bff5fe5eacf3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM2MzI3NDUsIm5iZiI6MTcyMzYzMjQ0NSwicGF0aCI6Ii8xNjU2NTA2NDYvMzU3Nzc2MjMzLTY3ZDM2NDllLTUyNWYtNDQ5OS1hMDdiLWJmZjVmZTVlYWNmMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxNFQxMDQ3MjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNDM1NWMzYTE2OThiMmNkYmM5MDkyYTE3ODgyMjhiYmZkNDMyOTZlMmFlYjAzMTA2ZWIxNTVmOTMzMTc4NWEyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.5HOtZvoWj4DXgi-v-hdD_9vFw3ITSIvMdZiP9x_XEEw">
> > > 补充信息：
> > > 
> > > 1. 如果使用本地数据库，可以正常查询数据
> > > 2. 更换成公司云数据库（都是mysql），就会提示数据库连接失败，但是在api里手动创建注册一个连接，也能正常查询
> > 
> > 
> > 这么看来更像是数据库连接配置问题，你可以试试将手动创建注册链接的配置替换extend/datebase/init.py 中的连接配置
> 
> 手动替换extend/datebase/init.py 中的连接配置，可以正常连接到数据库并且查询到了，但这个很奇怪，我也尝试将他们都打印出来对比下是哪个环节传递出的问题

数据库的密码认证方式，数据库的版本等细节问题可以先拍查下
